//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMonitor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditPolicy
    {
        public long ID { get; set; }
        public string APName { get; set; }
        public Nullable<long> SCID { get; set; }
        public string APUser { get; set; }
        public string APSchema { get; set; }
        public string APObjectName { get; set; }
        public string APColumnName { get; set; }
        public string APCondition { get; set; }
        public string APStatement { get; set; }
        public string APWhen { get; set; }
    }
}
