//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMonitor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public long ID { get; set; }
        public string DTypeCode { get; set; }
        public string DTypeName { get; set; }
        public string DCode { get; set; }
        public string DName { get; set; }
        public Nullable<long> DHasChild { get; set; }
        public Nullable<long> DParentID { get; set; }
        public Nullable<long> DEnable { get; set; }
    }
}
