//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMonitor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.ModuleAuthority = new HashSet<ModuleAuthority>();
        }
    
        public long ID { get; set; }
        public string MName { get; set; }
        public string MUrl { get; set; }
        public string MType { get; set; }
        public string MIcon { get; set; }
        public string MIconType { get; set; }
        public Nullable<long> MLevel { get; set; }
        public Nullable<long> MParentID { get; set; }
        public Nullable<long> MSortingNumber { get; set; }
        public Nullable<long> IsEnabled { get; set; }
        public Nullable<long> CreatorID { get; set; }
        public string CreationTime { get; set; }
        public Nullable<long> EditorID { get; set; }
        public string EditingTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleAuthority> ModuleAuthority { get; set; }
    }
}
