//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMonitor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionConnection
    {
        public long ID { get; set; }
        public string SCName { get; set; }
        public string SCHostName { get; set; }
        public Nullable<long> SCPort { get; set; }
        public string SCDBType { get; set; }
        public string SCServiceName { get; set; }
        public string SCRole { get; set; }
        public string SCSID { get; set; }
        public string SCUser { get; set; }
        public string SCPassword { get; set; }
        public Nullable<long> CreatorID { get; set; }
        public string CreationTime { get; set; }
        public Nullable<long> EditorID { get; set; }
        public string EditingTime { get; set; }
    }
}
